import { Metadata } from "next";
import { cookies } from "next/headers";
import React, { Suspense } from "react";
import { Refine } from "@refinedev/core";
import { DevtoolsProvider } from "@providers/devtools";
import { RefineKbar, RefineKbarProvider } from "@refinedev/kbar";
import { ThemedTitleV2, useNotificationProvider } from "@refinedev/antd";
import routerProvider from "@refinedev/nextjs-router";

import { dataProvider } from "@providers/data-provider";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import "@refinedev/antd/dist/reset.css";
import { AppIcon } from "@components/app-icon";
import { ColorModeContextProvider } from "@contexts/color-mode";

export const metadata: Metadata = {
  title: "Refine",
  description: "Generated by create refine app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const theme = cookieStore.get("theme");
  const defaultMode = theme?.value === "dark" ? "dark" : "light";

  return (
    <html lang="en">
      <body>
        <Suspense>
          <RefineKbarProvider>
            <AntdRegistry>
              <ColorModeContextProvider defaultMode={defaultMode}>
                <DevtoolsProvider>
                  <Refine
                    routerProvider={routerProvider}
                    dataProvider={dataProvider}
                    notificationProvider={useNotificationProvider}
                    resources={[
                      {
                        name: "vote",
                        list: "/vote",
                        meta: { label: "Vote" },
                      },
                      {
                        name: "eduid",
                        list: "/eduid",
                        create: "/eduid/create",
                        edit: "/eduid/edit",
                        show: "/eduid/show",
                        meta: { label: "EduID" },
                      },
                      {
                        name: "edupay",
                        list: "/edupay",
                        meta: { label: "EduPay" },
                      },
                      {
                        name: "grant",
                        list: "/grant",
                        meta: { label: "Grant" },
                      },
                      {
                        name: "edumarket",
                        list: "/edumarket",
                        meta: { label: "EduMarket" },
                      },
                      {
                        name: "home",
                        list: "/home",
                        meta: { label: "Home" },
                      },
                      {
                        name: "nodeinfo",
                        list: "/nodeinfo",
                        meta: { label: "Node Info" },
                      },
                      {
                        name: "contracts",
                        list: "/contracts",
                        show: "/contracts/:address",
                        meta: { label: "Smart Contracts" },
                      },
                      {
                        name: "eduadmission",
                        list: "/eduadmission",
                        meta: { label: "EduAdmission" },
                      },
                      {
                        name: "certificates",
                        list: "/certificates",
                        meta: { label: "Certificates" },
                      },
                      {
                        name: "course-completion",
                        list: "/course-completion",
                        meta: { label: "Course Completion" },
                      },
                      {
                        name: "degree-issuance",
                        list: "/degree-issuance",
                        meta: { label: "Degree Issuance" },
                      },
                      {
                        name: "upload",
                        list: "/upload",
                        meta: { label: "Upload" },
                      },
                      {
                        name: "researchledger",
                        list: "/researchledger",
                        meta: { label: "Research Ledger" },
                      },
                      {
                        name: "blog_posts",
                        list: "/blog-posts",
                        create: "/blog-posts/create",
                        edit: "/blog-posts/edit/:id",
                        show: "/blog-posts/show/:id",
                        meta: {
                          canDelete: true,
                        },
                      },
                      {
                        name: "categories",
                        list: "/categories",
                        create: "/categories/create",
                        edit: "/categories/edit/:id",
                        show: "/categories/show/:id",
                        meta: {
                          canDelete: true,
                        },
                      },
                    ]}
                    options={{
                      syncWithLocation: true,
                      warnWhenUnsavedChanges: true,
                      useNewQueryKeys: true,
                      projectId: "2Al7Hp-6aRhf6-4R1cIN",
                      title: { text: "Refine Project", icon: <AppIcon /> },
                    }}
                  >
                    {children}
                    <RefineKbar />
                  </Refine>
                </DevtoolsProvider>
              </ColorModeContextProvider>
            </AntdRegistry>
          </RefineKbarProvider>
        </Suspense>
      </body>
    </html>
  );
}
