#!/bin/sh
# Contract environment variables generated at Wed Jun 18 03:14:46 UTC 2025
# This file is automatically generated by entrypoint_core.sh

export EDUADMISSION_CONTRACT_ADDR=cosmos11innvpn6qidskr00qi8inlrmo9ia9pep9wxjd3
export EDUID_CONTRACT_ADDR=cosmos1e2349lwkx3duh4xslyxwjnfmrjzwtyeibu9tq0
export EDUCERT_CONTRACT_ADDR=cosmos1o3fyi3uhpuyvtuubi7xdg2f5bxie8ovkyitsbo
export EDUPAY_CONTRACT_ADDR=cosmos1fia520u7jvxll6jyr6gj62zm3zd0kr4fl459fz
export EDUMARKET_CONTRACT_ADDR=[Entrypoint] Deploying contract edumarket from /code/cosmwasm-contracts/edumarket/artifacts/edumarket.wasm
[Entrypoint] wasmd not available, using mock deployment
cosmos17oa565xvjx4ag6gpcazhhjkrbhjxnw6sy368c5
export RESEARCHLEDGER_CONTRACT_ADDR=cosmos1abtei3amhzhezu6q0eu535nxn2xr0lp824sok6
export GRANT_CONTRACT_ADDR=[Entrypoint] Deploying contract grant from /code/cosmwasm-contracts/grant/artifacts/grant.wasm
[Entrypoint] wasmd not available, using mock deployment
cosmos1687ftz8k1c7ysgghm1xt88p2gtjfztil62m0jc
export UPLOAD_CONTRACT_ADDR=[Entrypoint] Deploying contract upload from /code/cosmwasm-contracts/upload/artifacts/upload.wasm
[Entrypoint] wasmd not available, using mock deployment
cosmos14ycf5ibxrklszyugr19tyfevcilfws3hmbc9qv
export NODEINFO_CONTRACT_ADDR=[Entrypoint] Deploying contract nodeinfo from /code/cosmwasm-contracts/nodeinfo/artifacts/nodeinfo.wasm
[Entrypoint] wasmd not available, using mock deployment
cosmos1qcx0pegt90ggiqnn0yslcr4fcblscqdtd5af8g
