#!/bin/sh
# Contract environment variables generated at Wed Jun 18 11:16:27 UTC 2025
# This file is automatically generated by entrypoint_core.sh

export EDUADMISSION_CONTRACT_ADDR=cosmos1kz5smod9pj0vt5aboer2svnpr52bhrtqjp5cs0
export EDUID_CONTRACT_ADDR=cosmos1zwju01hxwu9l6xvjha7ehe8uqo1rpr09gtta6o
export EDUCERT_CONTRACT_ADDR=cosmos1oze9zuf7ae5urytvetq7hjnik0rnocty83z6r0
export EDUPAY_CONTRACT_ADDR=cosmos1mp75wi9hr1wnuhwhj9ybmu0ncy2ivdhocvtsko
export EDUMARKET_CONTRACT_ADDR=[Entrypoint] Deploying contract edumarket from /code/cosmwasm-contracts/edumarket/artifacts/edumarket.wasm
[Entrypoint] wasmd not available, using mock deployment
cosmos1t3rxxfg47s2fy4io1dddn7d2w1lq28x8e13kjp
export RESEARCHLEDGER_CONTRACT_ADDR=cosmos15xgxmx5muhx2umo2w1uorn2oj2rcbnl5n4blbp
export GRANT_CONTRACT_ADDR=[Entrypoint] Deploying contract grant from /code/cosmwasm-contracts/grant/artifacts/grant.wasm
[Entrypoint] wasmd not available, using mock deployment
cosmos1mwqbfx46180oc6ydtt2g7gdktj8xesr7qx7o3w
export UPLOAD_CONTRACT_ADDR=[Entrypoint] Deploying contract upload from /code/cosmwasm-contracts/upload/artifacts/upload.wasm
[Entrypoint] wasmd not available, using mock deployment
cosmos1545ffldw3ywggco2ois9ucgpvppl8fn3e9n1ry
export NODEINFO_CONTRACT_ADDR=[Entrypoint] Deploying contract nodeinfo from /code/cosmwasm-contracts/nodeinfo/artifacts/nodeinfo.wasm
[Entrypoint] wasmd not available, using mock deployment
cosmos1n2tu5w7tgeea59ttfwckfz6804ix8b1oqf4wss
