FROM python:3.10

WORKDIR /app

COPY . .

# COPY ../deploy/config/initial_nodes.json /app/config/initial_nodes.json

# COPY ../deploy/contract_addresses/contract_addresses.json /app/contract_addresses/contract_addresses.json

RUN pip install --no-cache-dir -r requirements.txt

RUN python generate_dummy_data.py || true

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]