#!/bin/sh
# Contract environment variables generated at Wed Jun 18 15:01:32 UTC 2025
# This file is automatically generated by entrypoint_core.sh

export EDUADMISSION_CONTRACT_ADDR=cosmos1gqvm21h4ffos7b4m6ih6ihtvd1srysukk22bn8
export EDUID_CONTRACT_ADDR=cosmos1dpwznhvlr1bqckms029o9jo8k5eaj8ly9o7tea
export EDUCERT_CONTRACT_ADDR=cosmos1f5h4wmbtvp1yieu7f8wr382jvhtlmtd349mql4
export EDUPAY_CONTRACT_ADDR=cosmos17v48991jhcroditwx6nn2q3sgbo0okzs26bjwg
export EDUMARKET_CONTRACT_ADDR=[Entrypoint] Deploying contract edumarket from /code/cosmwasm-contracts/edumarket/artifacts/edumarket.wasm
[Entrypoint] wasmd not available, using mock deployment
cosmos18vlvzcwma9rgby94g3gsx5e815p5cu5th2zk9x
export RESEARCHLEDGER_CONTRACT_ADDR=cosmos1z35eq41uwwhcq3nedv51bsiqpvzrg12p7oi4xn
export GRANT_CONTRACT_ADDR=[Entrypoint] Deploying contract grant from /code/cosmwasm-contracts/grant/artifacts/grant.wasm
[Entrypoint] wasmd not available, using mock deployment
cosmos1b5m8t72tn0mkmv4zmdtyuk46fd5s2733slhvip
export UPLOAD_CONTRACT_ADDR=[Entrypoint] Deploying contract upload from /code/cosmwasm-contracts/upload/artifacts/upload.wasm
[Entrypoint] wasmd not available, using mock deployment
cosmos14y1hpo9mw0vbjiwqb21jascrc5ze8vf1zppmqr
export NODEINFO_CONTRACT_ADDR=[Entrypoint] Deploying contract nodeinfo from /code/cosmwasm-contracts/nodeinfo/artifacts/nodeinfo.wasm
[Entrypoint] wasmd not available, using mock deployment
cosmos121mrpi47wbmfirklppl3pougpqidvgmiq5c7ow
